/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ConversationRouteRouteImport } from './routes/_conversation/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicRulesRouteImport } from './routes/_public/rules'
import { Route as PublicRoomsRouteImport } from './routes/_public/rooms'
import { Route as ConversationRouletteIdRouteImport } from './routes/_conversation/roulette.$id'
import { Route as ConversationRoomIdRouteImport } from './routes/_conversation/room.$id'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRouteRoute = ConversationRouteRouteImport.update({
  id: '/_conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRulesRoute = PublicRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRoomsRoute = PublicRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ConversationRouletteIdRoute = ConversationRouletteIdRouteImport.update({
  id: '/roulette/$id',
  path: '/roulette/$id',
  getParentRoute: () => ConversationRouteRoute,
} as any)
const ConversationRoomIdRoute = ConversationRoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => ConversationRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/rooms': typeof PublicRoomsRoute
  '/rules': typeof PublicRulesRoute
  '/': typeof PublicIndexRoute
  '/room/$id': typeof ConversationRoomIdRoute
  '/roulette/$id': typeof ConversationRouletteIdRoute
}
export interface FileRoutesByTo {
  '/rooms': typeof PublicRoomsRoute
  '/rules': typeof PublicRulesRoute
  '/': typeof PublicIndexRoute
  '/room/$id': typeof ConversationRoomIdRoute
  '/roulette/$id': typeof ConversationRouletteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_conversation': typeof ConversationRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/rooms': typeof PublicRoomsRoute
  '/_public/rules': typeof PublicRulesRoute
  '/_public/': typeof PublicIndexRoute
  '/_conversation/room/$id': typeof ConversationRoomIdRoute
  '/_conversation/roulette/$id': typeof ConversationRouletteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/rooms' | '/rules' | '/' | '/room/$id' | '/roulette/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/rooms' | '/rules' | '/' | '/room/$id' | '/roulette/$id'
  id:
    | '__root__'
    | '/_conversation'
    | '/_public'
    | '/_public/rooms'
    | '/_public/rules'
    | '/_public/'
    | '/_conversation/room/$id'
    | '/_conversation/roulette/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConversationRouteRoute: typeof ConversationRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_conversation': {
      id: '/_conversation'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ConversationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/rules': {
      id: '/_public/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof PublicRulesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/rooms': {
      id: '/_public/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof PublicRoomsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_conversation/roulette/$id': {
      id: '/_conversation/roulette/$id'
      path: '/roulette/$id'
      fullPath: '/roulette/$id'
      preLoaderRoute: typeof ConversationRouletteIdRouteImport
      parentRoute: typeof ConversationRouteRoute
    }
    '/_conversation/room/$id': {
      id: '/_conversation/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof ConversationRoomIdRouteImport
      parentRoute: typeof ConversationRouteRoute
    }
  }
}

interface ConversationRouteRouteChildren {
  ConversationRoomIdRoute: typeof ConversationRoomIdRoute
  ConversationRouletteIdRoute: typeof ConversationRouletteIdRoute
}

const ConversationRouteRouteChildren: ConversationRouteRouteChildren = {
  ConversationRoomIdRoute: ConversationRoomIdRoute,
  ConversationRouletteIdRoute: ConversationRouletteIdRoute,
}

const ConversationRouteRouteWithChildren =
  ConversationRouteRoute._addFileChildren(ConversationRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicRoomsRoute: typeof PublicRoomsRoute
  PublicRulesRoute: typeof PublicRulesRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicRoomsRoute: PublicRoomsRoute,
  PublicRulesRoute: PublicRulesRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ConversationRouteRoute: ConversationRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
