/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RouletteIdRouteImport } from './routes/roulette.$id'
import { Route as RoomIdRouteImport } from './routes/room.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RouletteIdRoute = RouletteIdRouteImport.update({
  id: '/roulette/$id',
  path: '/roulette/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdRoute = RoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/room/$id': typeof RoomIdRoute
  '/roulette/$id': typeof RouletteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/room/$id': typeof RoomIdRoute
  '/roulette/$id': typeof RouletteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/room/$id': typeof RoomIdRoute
  '/roulette/$id': typeof RouletteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/room/$id' | '/roulette/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/room/$id' | '/roulette/$id'
  id: '__root__' | '/' | '/room/$id' | '/roulette/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomIdRoute: typeof RoomIdRoute
  RouletteIdRoute: typeof RouletteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roulette/$id': {
      id: '/roulette/$id'
      path: '/roulette/$id'
      fullPath: '/roulette/$id'
      preLoaderRoute: typeof RouletteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$id': {
      id: '/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomIdRoute: RoomIdRoute,
  RouletteIdRoute: RouletteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
