/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ConversationRouteImport } from './routes/_conversation'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicRulesRouteImport } from './routes/_public/rules'
import { Route as ConversationRouletteIdRouteImport } from './routes/_conversation/roulette.$id'
import { Route as ConversationRoomIdRouteImport } from './routes/_conversation/room.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/_conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRulesRoute = PublicRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => PublicRoute,
} as any)
const ConversationRouletteIdRoute = ConversationRouletteIdRouteImport.update({
  id: '/roulette/$id',
  path: '/roulette/$id',
  getParentRoute: () => ConversationRoute,
} as any)
const ConversationRoomIdRoute = ConversationRoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => ConversationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/rules': typeof PublicRulesRoute
  '/': typeof PublicIndexRoute
  '/room/$id': typeof ConversationRoomIdRoute
  '/roulette/$id': typeof ConversationRouletteIdRoute
}
export interface FileRoutesByTo {
  '/rules': typeof PublicRulesRoute
  '/': typeof PublicIndexRoute
  '/room/$id': typeof ConversationRoomIdRoute
  '/roulette/$id': typeof ConversationRouletteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_conversation': typeof ConversationRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/rules': typeof PublicRulesRoute
  '/_public/': typeof PublicIndexRoute
  '/_conversation/room/$id': typeof ConversationRoomIdRoute
  '/_conversation/roulette/$id': typeof ConversationRouletteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/rules' | '/' | '/room/$id' | '/roulette/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/rules' | '/' | '/room/$id' | '/roulette/$id'
  id:
    | '__root__'
    | '/_conversation'
    | '/_public'
    | '/_public/rules'
    | '/_public/'
    | '/_conversation/room/$id'
    | '/_conversation/roulette/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConversationRoute: typeof ConversationRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_conversation': {
      id: '/_conversation'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/rules': {
      id: '/_public/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof PublicRulesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_conversation/roulette/$id': {
      id: '/_conversation/roulette/$id'
      path: '/roulette/$id'
      fullPath: '/roulette/$id'
      preLoaderRoute: typeof ConversationRouletteIdRouteImport
      parentRoute: typeof ConversationRoute
    }
    '/_conversation/room/$id': {
      id: '/_conversation/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof ConversationRoomIdRouteImport
      parentRoute: typeof ConversationRoute
    }
  }
}

interface ConversationRouteChildren {
  ConversationRoomIdRoute: typeof ConversationRoomIdRoute
  ConversationRouletteIdRoute: typeof ConversationRouletteIdRoute
}

const ConversationRouteChildren: ConversationRouteChildren = {
  ConversationRoomIdRoute: ConversationRoomIdRoute,
  ConversationRouletteIdRoute: ConversationRouletteIdRoute,
}

const ConversationRouteWithChildren = ConversationRoute._addFileChildren(
  ConversationRouteChildren,
)

interface PublicRouteChildren {
  PublicRulesRoute: typeof PublicRulesRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicRulesRoute: PublicRulesRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConversationRoute: ConversationRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
